---
##################
# Basic Settings #
##################

# Image resolution Set to empty object (`{ }`) to use default resolution.
resolution: { 
  width: 3280,
  height: 2464
}

# The number of images to capture.
total_images: 1440

# The interval between captures (in seconds).
interval: 10

# Whether to create an animated gif after capturing the time-lapse images.
create_gif: False

# Whether to create an video after capturing the time-lapse images.
create_video: False

#####################
# Advanced settings #
#####################

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 100

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 0

# White balance. Set to empty object (`{ }`) to use auto white balance.
white_balance: { 
  red_gain: 1.5,
  blue_gain: 1.3
  }

# Rotate the images taken by the camera. Possible value are 0, 90, 180 or 270
rotation: 0
